production:
  adapter: mysql2
  database: lab_systems
  host: localhost
  username: lab_systems
  password: "2020Q3Qct!"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4

development:
  adapter: "sqlite3"
  database: "db/systems.sqlite3"
  timeout: 20000

test:
  adapter: "sqlite3"
  database: "db/systems.sqlite3"
  timeout: 20000

